export const inputType = {
  BOOLEAN: "BOOLEAN",
  STRING: "STRING",
  INTEGER: "INTEGER",
  DECIMAL: "DECIMAL",
  DATE: "DATE",
  DROPDOWN: "DROPDOWN",
  SELECT: "SELECT",
  MULTISELECT: "MULTISELECT",
};
