# name: "🚀 deploy to GH Pages"

# on:
#   push:
#     branches:
#       - 'main'

# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2.3.1

#       - name: Install and Build
#         run: |
#           npm install
#           npm run build-storybook
#         env:
#           NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }} # You need to set this in your repo settings
#       - name: Deploy
#         uses: JamesIves/github-pages-deploy-action@4.1.4
#         with:
#           branch: gh-pages
#           folder: docs-build
#           clean: true
#           #target_folder: docs
