name: "🚀 publish to NPM"

on:
  push:
    branches:
      - master
      - CloneFirstCommit
      - GoAirComponents_branch

jobs:
  release:
    name: 🚀 publish to NPM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 14.15.1
          registry-url: https://registry.npmjs.org
      # clean install of your projects' deps. We use "npm ci" to avoid package lock changes
      - run: npm ci
      - run: npm run build
      - name: Publish if version has been updated
        uses: houtianze/npm-publish-action@master
        with: # All of theses inputs are optional
          tag_name: "v%s"
          tag_message: "v%s"
          commit_pattern: "^(?:Release|Version) (\\S+)"
        # - name: 🚀 publish
        #   run: npm publish --access public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Leave this as is, it's automatically generated
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }} # You need to set this in your repo settings
